FROM bitnami/spark:3.5.1

USER root

RUN apt-get update && apt-get install -y python3 python3-pip openjdk-17-jdk && apt-get clean

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

#RUN pip3 install pyspark==3.5.1

USER 1001