name: Deploy Fraud Model to Databricks

on:
  push:
    paths:
      - './dags/scripts/fraud_logreg_job.py'
      - './dags/scripts/fraud_job.yaml'

jobs:
  deploy-to-databricks:
    name: Upload + Trigger Fraud Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@v1
        with:
          databricks-host: ${{ secrets.DATABRICKS_HOST }}
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}

      - name: Upload Python Job Script to DBFS
        run: |
          echo "📤 Uploading fraud_logreg_job.py to DBFS"
          databricks fs cp fraud_logreg_job.py dbfs:/fraud-miner/fraud_logreg_job.py --overwrite

      - name: Create or Update Job from YAML
        run: |
          echo "⚙️ Deploying job using fraud_job.yaml"
          databricks jobs create --json-file fraud_job.yaml || echo "🟡 Job may already exist."

      - name: Run Databricks Job
        run: |
          echo "🚀 Triggering job..."
          JOB_ID=$(databricks jobs list --output JSON | jq -r '.jobs[] | select(.settings.name=="Fraud_model") | .job_id')
          if [ -z "$JOB_ID" ]; then
            echo "❌ Job not found. Aborting run."
            exit 1
          fi
          databricks jobs run-now --job-id "$JOB_ID"
